create table if not exists public.guest_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  attendance text not null check (attendance in ('attending', 'not_attending')),
  guest_count integer not null default 0 check (guest_count between 0 and 5),
  message text not null check (char_length(message) between 3 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.guest_messages enable row level security;

-- New Supabase projects no longer expose public tables automatically. Keep the
-- Data API surface explicit: anonymous guests may only read and submit the four
-- RSVP fields. They cannot set ids, timestamps, or moderation state.
revoke all privileges on table public.guest_messages from public, anon, authenticated;
revoke all privileges on sequence public.guest_messages_id_seq from public, anon, authenticated;

grant usage on schema public to anon;
grant select on table public.guest_messages to anon;
grant insert (name, attendance, guest_count, message)
on table public.guest_messages to anon;
grant usage, select on sequence public.guest_messages_id_seq to anon;

drop policy if exists "Public can read approved messages" on public.guest_messages;
create policy "Public can read approved messages"
on public.guest_messages for select
to anon
using (approved = true);

drop policy if exists "Public can submit messages" on public.guest_messages;
create policy "Public can submit messages"
on public.guest_messages for insert
to anon
with check (
  approved = true
  and char_length(name) between 2 and 80
  and char_length(message) between 3 and 500
  and guest_count between 0 and 5
  and attendance in ('attending', 'not_attending')
);

create index if not exists guest_messages_created_at_idx
on public.guest_messages (created_at desc);
