create table if not exists public.guest_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  attendance text not null check (attendance in ('attending', 'not_attending')),
  guest_count integer not null default 0 check (guest_count between 0 and 5),
  message text not null check (char_length(message) between 3 and 500),
  approved boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.guest_messages enable row level security;

create policy "Public can read approved messages"
on public.guest_messages for select
to anon
using (approved = true);

create policy "Public can submit messages"
on public.guest_messages for insert
to anon
with check (
  approved = true
  and char_length(name) between 2 and 80
  and char_length(message) between 3 and 500
  and guest_count between 0 and 5
  and attendance in ('attending', 'not_attending')
);

create index if not exists guest_messages_created_at_idx
on public.guest_messages (created_at desc);
